// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspcoredemo.Data;

#nullable disable

namespace aspcoredemo.Migrations
{
    [DbContext(typeof(studentdbcontext))]
    [Migration("20240207054344_addstudent1")]
    partial class addstudent1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("aspcoredemo.Models.studentregister", b =>
                {
                    b.Property<int>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_id"), 1L, 1);

                    b.Property<string>("student_branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_id");

                    b.ToTable("student");
                });
#pragma warning restore 612, 618
        }
    }
}
